/**
 * Mock data for UI development — used until Supabase is connected.
 * Replace with real searchByFitment() calls once Edge Functions are deployed.
 */

import type { PartGroup, RankedOffer } from "./search";

const makeOffer = (overrides: Partial<RankedOffer>): RankedOffer => ({
  id: Math.random().toString(36).slice(2),
  source: "autodoc",
  url: "#",
  title: "Disque de frein avant",
  part_number: "34116792217",
  brand: "Zimmermann",
  condition: "NEW",
  part_type: "NEW_OEM",
  price_eur: 32.9,
  shipping_cost_eur: 5.9,
  seller_name: "AutoDoc",
  seller_country: "DE",
  image_urls: null,
  stock_qty: 12,
  warranty_months: 24,
  is_rec: false,
  rec_grade: null,
  rec_donor_vin: null,
  rec_donor_km: null,
  rec_dismantler: null,
  rec_dismantler_cert: null,
  rec_recall_check: null,
  score: 18.4,
  checkout_type: "affiliate",
  commercial_boost: 0,
  is_sponsored: false,
  ...overrides,
});

export const MOCK_OFFERS: RankedOffer[] = [
  makeOffer({
    source: "autodoc",
    seller_name: "AutoDoc",
    price_eur: 32.9,
    shipping_cost_eur: 5.9,
    score: 21.2,
    checkout_type: "affiliate",
    commercial_boost: 3,
    is_sponsored: true,
    warranty_months: 24,
  }),
  makeOffer({
    source: "mister_auto",
    seller_name: "Mister Auto",
    price_eur: 28.5,
    shipping_cost_eur: 0,
    score: 19.8,
    checkout_type: "affiliate",
    warranty_months: 12,
  }),
  makeOffer({
    source: "oscaro",
    seller_name: "Oscaro",
    price_eur: 35.2,
    shipping_cost_eur: 4.5,
    score: 17.1,
    checkout_type: "affiliate",
    warranty_months: 24,
  }),
  makeOffer({
    source: "ebay_fr",
    seller_name: "pieces-auto-pro",
    price_eur: 24.99,
    shipping_cost_eur: 7.5,
    score: 14.3,
    checkout_type: "affiliate",
    condition: "USED",
    part_type: "USED",
    warranty_months: null,
  }),
  makeOffer({
    source: "ovoko",
    seller_name: "RecyclAuto SAS",
    price_eur: 19.0,
    shipping_cost_eur: 9.9,
    score: 16.5,
    checkout_type: "affiliate",
    condition: "REC",
    part_type: "REC",
    is_rec: true,
    rec_grade: "A",
    rec_donor_vin: "WVWZZZ1KZG1234567",
    rec_donor_km: 68000,
    rec_dismantler: "RecyclAuto SAS",
    rec_dismantler_cert: "VHU-FR-044-2019",
    rec_recall_check: true,
    warranty_months: 12,
  }),
];

export const MOCK_GROUPS: PartGroup[] = [
  {
    part_number_normalized: "34116792217",
    part_name: "Disque de frein avant Zimmermann",
    brand_name: "Zimmermann",
    category_slug: "disques-de-frein",
    low_price_eur: 19.0,
    offer_count: 5,
    has_rec: true,
    image_url: null,
    offers: MOCK_OFFERS,
  },
  {
    part_number_normalized: "34116850566",
    part_name: "Disque de frein avant Brembo",
    brand_name: "Brembo",
    category_slug: "disques-de-frein",
    low_price_eur: 41.5,
    offer_count: 3,
    has_rec: false,
    image_url: null,
    offers: [
      makeOffer({ brand: "Brembo", part_number: "34116850566", price_eur: 41.5, shipping_cost_eur: 0, seller_name: "Oscaro", score: 20.1 }),
      makeOffer({ brand: "Brembo", part_number: "34116850566", price_eur: 49.9, shipping_cost_eur: 5.9, seller_name: "AutoDoc", score: 17.3, commercial_boost: 3, is_sponsored: true }),
      makeOffer({ brand: "Brembo", part_number: "34116850566", price_eur: 44.0, shipping_cost_eur: 4.5, seller_name: "Mister Auto", score: 15.9 }),
    ],
  },
  {
    part_number_normalized: "1163235012",
    part_name: "Disque de frein avant Bosch",
    brand_name: "Bosch",
    category_slug: "disques-de-frein",
    low_price_eur: 26.8,
    offer_count: 2,
    has_rec: false,
    image_url: null,
    offers: [
      makeOffer({ brand: "Bosch", part_number: "1163235012", price_eur: 26.8, shipping_cost_eur: 5.9, seller_name: "AutoDoc", score: 19.0 }),
      makeOffer({ brand: "Bosch", part_number: "1163235012", price_eur: 31.5, shipping_cost_eur: 0, seller_name: "Oscaro", score: 16.4 }),
    ],
  },
];
